#!/usr/bin/ruby
require "yaml"

def yaml_data
	if ARGV[0]
		YAML.load_file(ARGV[0])
	else
		nil
	end
end

def recipe
	if ARGV[1] == "--force"
		give_me_recipe_anyway
	else
		give_me_recipe
	end
end

def give_me_recipe
	arr = yaml_data.to_a.sample(3)
	sum = arr.inject(0){|sum,x| sum + x[1]}
	arr.select{|names,value| puts value } if sum == 0 or puts "not possible"
end

def give_me_recipe_anyway
	while
		arr = yaml_data.to_a.sample(3)
		sum = arr.inject(0){|sum,x| sum + x[1]}
		break if sum == 0
	end
	arr.select{|names,value| puts names }
end

recipe
