#!/usr/bin/ruby
require "yaml"

def yaml_data
  if ARGV[0]
    YAML.load_file(ARGV[0])
  else
    nil
  end
end

def recipe?
  if ARGV[1] == "--force"
    ensure_give_me_recipe!
  else
    give_me_recipe
  end
end

def set_data_and_sum
  @arr = yaml_data.to_a.sample(3)
  @sum = @arr.inject(0){|sum,x| sum + x[1]}
end

def give_me_recipe
  set_data_and_sum
  @arr.select{|names,value| puts names } if @sum == 0 or puts "not possible"
end

def ensure_give_me_recipe!
  while
    set_data_and_sum
    break if @sum == 0
  end
  @arr.select{|names,value| puts names }
end

recipe?
